### ISSUE TITLE
Blank Page Error

### ISSUE THREAD

**Issue by madsonbruno** [themejack/fiera#2]
Everytime that I'm installing this theme I'm getting a blank page, and I can't even acess the admin. When the debug mode is active I get the following error message:

`Fatal error: Can't use function return value in write context in /home/wp-content/themes/fiera-master/inc/extras.php on line 153`

So I must to rename the theme folder to back to the wordpress default theme. But this amazing theme, fiera, never works. This is just happening in this theme fiera, I've installed the others themes(karta, pine,briar) and they're fine. 
Can someone help me? =(

**Comment by madsonbruno** [comment]
Btw, this says:

`if ( ! empty( trim( $tab['title'] ) ) ) {`

**Comment by anteprimorac** [comment]
Fixed in release v1.0.1. Also please look at requirements section in README.md. This theme will not work on PHP 5.2.x because our library for metaboxes and fields is requiring PHP 5.3.x.

**Comment by madsonbruno** [comment]
Thanks  @anteprimorac  4 the awesome quick answer! :+1: 
It's really solve that bug. But I'm still getting the following error:

`Warning: require(OmniBuilder/builder.php): failed to open stream: No such file or directory in /wp-content/themes/fiera/inc/metaboxes.php on line 10 Fatal error: require(): Failed opening required 'OmniBuilder/builder.php' (include_path='.:/usr/share/php:/usr/share/pear') in /wp-content/themes/fiera/inc/metaboxes.php on line 10`

PS: I'm running WordPress 4.5.3 on PHP 5.3.2-1ubuntu4.24 | Apache/2.2.14 (Ubuntu) PHP/5.3.2-1ubuntu4.24 with Suhosin-Patch mod_perl/2.0.4 Perl/v5.10.1 | MySQL 5.1.73 

Am I doing something wrong!?

**Comment by anteprimorac** [comment]
Hi @madsonbruno,
you probably downloaded github export file, but you need to download attached .zip or .tar.gz file from release. Here is a link to .zip file from v1.0.1 release https://github.com/themejack/fiera/releases/download/v1.0.1/fiera-1.0.1.zip

**Comment by madsonbruno** [comment]
@anteprimorac ,

I downloaded and installed the most recent attached .zip file from release. The name is fiera-1.0.1.zip. 
I do it again with the file that you put the link here. But I till getting the same error message:

`Warning: require(OmniBuilder/builder.php): failed to open stream: No such file or directory in /home/shxxi/wp-content/themes/fiera/inc/metaboxes.php on line 10 Fatal error: require(): Failed opening required 'OmniBuilder/builder.php' (include_path='.:/usr/share/php:/usr/share/pear') in /home/shxxi/wp-content/themes/fiera/inc/metaboxes.php on line 10` 

:(

**Comment by madsonbruno** [comment]
PS: I tried a different server, PHP 5.6, but I'm still getting the same error. :x:

**Comment by anteprimorac** [comment]
@madsonbruno 
can you try new release v1.0.2?

**Comment by madsonbruno** [comment]
It's work, @anteprimorac ! :+1: 
I'm crying here! 
You're AWESOME, dude! Congrats!

**Comment by madsonbruno** [comment]
Sorry, it's me again... :grin: 
I have a question: Why I can't see the metaboxes? How can I add something?

**Comment by madsonbruno** [comment]
I must to activate something before?

**Comment by anteprimorac** [comment]
@madsonbruno 
metaboxes are only visible on front page. Create new page and set it as Front page in `Settings > Reading > Front page displays > A static page > Front page` select box.
